# Generated by Django 5.2 on 2025-05-02 11:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("message", models.CharField(max_length=200)),
                ("subject", models.CharField(max_length=200)),
                ("email", models.EmailField(max_length=254)),
                ("name", models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="Hotel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=220)),
                ("description", models.TextField()),
                ("image", models.ImageField(upload_to="destinations")),
                ("price", models.IntegerField()),
                ("rating", models.PositiveIntegerField(default="1")),
                ("location", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Hotel_info",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("duration", models.CharField(max_length=100)),
                ("location", models.CharField(max_length=255)),
                ("price", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Information",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("duration", models.CharField(max_length=100)),
                ("location", models.CharField(max_length=255)),
                ("price", models.IntegerField()),
                ("image", models.ImageField(upload_to="images")),
            ],
        ),
        migrations.CreateModel(
            name="Tour",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField()),
                ("image", models.ImageField(upload_to="destinations")),
                ("price", models.IntegerField()),
                ("rating", models.PositiveIntegerField(default="1")),
                (
                    "duration",
                    models.CharField(default="2 days 3 nights", max_length=50),
                ),
                ("location", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Tour_cat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Cat_name", models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name="Hotel_booking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                ("checkin", models.DateField()),
                ("checkout", models.DateField()),
                ("no_guest", models.IntegerField()),
                ("price", models.IntegerField()),
                ("total_price", models.IntegerField()),
                ("message", models.CharField(max_length=250)),
                ("is_booking", models.BooleanField(default=False)),
                (
                    "razorpay_order_id",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "payment_status",
                    models.CharField(
                        choices=[
                            ("Pending", "Pending"),
                            ("Completed", "Completed"),
                            ("Failed", "Failed"),
                        ],
                        default="Pending",
                        max_length=20,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Tour_booking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("f_name", models.CharField(max_length=30)),
                ("l_name", models.CharField(max_length=30)),
                ("phone", models.IntegerField()),
                ("email", models.EmailField(max_length=254)),
                ("destination", models.CharField(max_length=50)),
                ("no_person", models.IntegerField(default=1)),
                ("price", models.IntegerField()),
                ("t_price", models.IntegerField()),
                ("duration", models.CharField(max_length=100)),
                ("is_booking", models.BooleanField(default=False)),
                (
                    "razorpay_order_id",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "payment_status",
                    models.CharField(
                        choices=[
                            ("Pending", "Pending"),
                            ("Completed", "Completed"),
                            ("Failed", "Failed"),
                        ],
                        default="Pending",
                        max_length=20,
                    ),
                ),
                (
                    "Tour_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="traveler.tour"
                    ),
                ),
                (
                    "username",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="tour",
            name="Category_name",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tours",
                to="traveler.tour_cat",
            ),
        ),
    ]
